server {
    listen 80;
    server_name www-thehackspace.hosting.uniba.it 193.206.44.31;

    location = / {
        return 200 "CTF reverse proxy online\n";
        add_header Content-Type text/plain;
    }

    location = /harbor_gate {
        return 302 /harbor_gate/;
    }

    location /harbor_gate/ {
        proxy_pass http://127.0.0.1:8081/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Prefix /harbor_gate;
        proxy_redirect off;
    }

    location = /trident_notes {
	    return 302 /trident_notes/;
    }

    location /trident_notes/ {
        proxy_pass http://127.0.0.1:8082/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Prefix /trident_notes;
        proxy_redirect off;
    }

    location = /trident_check_1 {
	    return 302 /trident_check_1/;
    }

    location /trident_check_1/ {
        proxy_pass http://127.0.0.1:8083/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Prefix /trident_check_1;
        proxy_redirect off;
    }

    location = /trident_check_2 {
	    return 302 /trident_check_2/;
    }

    location /trident_check_2/ {
        proxy_pass http://127.0.0.1:8084/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Prefix /trident_check_2;
        proxy_redirect off;
    }

    location = /css_mdo/md5 {
        alias /home/d.posa/sscss_ctf_r-b/css_mdo/CTF_CSS_MDO_MD5.html;
        default_type text/html;
    }

    location = /css_mdo/inj {
        alias /home/d.posa/sscss_ctf_r-b/css_mdo/CTF_CSS_MDO_INJ.html;
        default_type text/html;
    }
}
